apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cognexa
resources:
  - namespace.yaml
  - configmap.yaml
  - server-deployment.yaml
  - server-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
  - autoscaling.yaml
  - availability.yaml
  - network-policy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: cognexa
      app.kubernetes.io/managed-by: kustomize
