apiVersion: v1
kind: Namespace
metadata:
  name: cognexa
  labels:
    app.kubernetes.io/part-of: cognexa
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
