apiVersion: v1
kind: Service
metadata:
  name: cognexa-server
  labels:
    app.kubernetes.io/name: cognexa-server
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cognexa-server
  ports:
    - name: http
      port: 4000
      targetPort: http
